-- 주보/오늘의 말씀/교독문이 코드에 하드코딩되어 있어서 매번 배포해야 수정 가능했던 문제를
-- 해결하기 위해, 세 콘텐츠를 관리자가 앱 화면에서 직접 편집할 수 있도록 테이블로 옮긴다.

-- 교독문 (예장통합 표준 교독문 137개 + 이후 추가분)
create table if not exists gyodokmun_readings (
  number int primary key,
  title text not null,
  lines jsonb not null,
  updated_at timestamptz not null default now()
);

alter table gyodokmun_readings enable row level security;

drop policy if exists "gyodokmun_select_all" on gyodokmun_readings;
create policy "gyodokmun_select_all"
on gyodokmun_readings for select
using (true);

drop policy if exists "gyodokmun_admin_write" on gyodokmun_readings;
create policy "gyodokmun_admin_write"
on gyodokmun_readings for all
using (exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true))
with check (exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true));

-- 오늘의 말씀에 쓰이는 성구 목록. 날짜(연중 몇 번째 날)를 이 목록 개수로 나눈 나머지로
-- 하나를 골라 보여주던 기존 방식(getTodayVerse)을 그대로 유지하되, 목록을 DB에서 가져온다.
create table if not exists daily_verses (
  id bigint generated by default as identity primary key,
  ref text not null,
  verse_text text not null,
  created_at timestamptz not null default now()
);

alter table daily_verses enable row level security;

drop policy if exists "daily_verses_select_all" on daily_verses;
create policy "daily_verses_select_all"
on daily_verses for select
using (true);

drop policy if exists "daily_verses_admin_write" on daily_verses;
create policy "daily_verses_admin_write"
on daily_verses for all
using (exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true))
with check (exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true));

-- 주보. 예배순서/교회소식/기도제목/섬김이/표어처럼 항목이 여러 개인 부분은 기존 페이지
-- 컴포넌트가 그대로 읽을 수 있도록 jsonb 하나(content)에 같은 모양으로 넣어둔다.
create table if not exists bulletins (
  id bigint generated by default as identity primary key,
  issue text not null,
  bulletin_date date not null,
  content jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists bulletins_date_idx on bulletins (bulletin_date desc);

alter table bulletins enable row level security;

drop policy if exists "bulletins_select_all" on bulletins;
create policy "bulletins_select_all"
on bulletins for select
using (true);

drop policy if exists "bulletins_admin_write" on bulletins;
create policy "bulletins_admin_write"
on bulletins for all
using (exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true))
with check (exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true));
