-- 앱 최초 진입 시 뜨는 공지 팝업 + 관리자 전용 공지 관리.
--
-- popup_notices: 누구나 읽을 수 있지만(팝업으로 공개 노출되어야 하므로),
-- 등록/수정/삭제는 관리자만 가능합니다.

create table if not exists popup_notices (
  id bigint generated by default as identity primary key,
  title text,
  image_path text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table popup_notices enable row level security;

drop policy if exists "popup_notices_select" on popup_notices;
create policy "popup_notices_select"
on popup_notices for select
using (true);

drop policy if exists "popup_notices_admin_write" on popup_notices;
create policy "popup_notices_admin_write"
on popup_notices for all
using (
  exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true)
)
with check (
  exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true)
);
