-- 게시판 탭 목록/이름/순서/활성화 여부를 관리자가 화면에서 직접 관리할 수 있게 하는 설정
-- 테이블. posts.category는 그대로 두고(이미 정상 동작 중인 실제 글 데이터), 이 테이블은
-- 어떤 탭을 어떤 이름·순서로 보여줄지만 담당한다. 멀티테넌시(church_id) 없음 — 이 교회
-- 하나만 쓰는 구조.
create table if not exists boards (
  id bigint generated by default as identity primary key,
  board_key text not null unique,
  board_name text not null,
  is_active boolean not null default true,
  display_order int not null default 0,
  created_at timestamptz not null default now()
);

alter table boards enable row level security;

drop policy if exists "boards_select_all" on boards;
create policy "boards_select_all"
on boards for select
using (true);

drop policy if exists "boards_admin_write" on boards;
create policy "boards_admin_write"
on boards for all
using (exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true))
with check (exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true));

-- 기존 4개 게시판을 그대로 등록 (이름/순서 동일)
insert into boards (board_key, board_name, display_order) values
  ('district', '구역게시판', 1),
  ('prayer', '기도게시판', 2),
  ('share', '나눔게시판', 3),
  ('suggestion', '교회제안', 4)
on conflict (board_key) do nothing;
