-- 게시글에 첨부파일을 여러 개 올릴 수 있도록 별도 테이블을 추가한다.
-- 기존 posts.attachment_url/attachment_name(단일 첨부)은 과거 글 호환을 위해
-- 그대로 두고, 새 글은 이 테이블만 사용한다.

create table if not exists post_attachments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references posts(id) on delete cascade,
  url text not null,
  name text not null,
  created_at timestamptz not null default now()
);

create index if not exists post_attachments_post_id_idx on post_attachments (post_id);

alter table post_attachments enable row level security;

-- 기본 조회는 게시글과 동일하게 열어두고(비공개 게시판은 아래 RESTRICTIVE로 가림),
-- 등록은 그 글의 작성자만 가능하게 한다.
drop policy if exists "post_attachments_select" on post_attachments;
create policy "post_attachments_select"
on post_attachments for select
using (true);

-- 교회제안(suggestion) 글의 첨부파일도 글 본문과 동일한 대상에게만 보이게 한다.
drop policy if exists "post_attachments_suggestion_private" on post_attachments;
create policy "post_attachments_suggestion_private"
on post_attachments as restrictive for select
using (
  not exists (select 1 from posts pt where pt.id = post_id and pt.category = 'suggestion')
  or exists (select 1 from posts pt where pt.id = post_id and pt.user_id = auth.uid())
  or exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true)
  or has_role('pastor_reply')
);

drop policy if exists "post_attachments_insert_own" on post_attachments;
create policy "post_attachments_insert_own"
on post_attachments for insert
with check (
  exists (select 1 from posts pt where pt.id = post_id and pt.user_id = auth.uid())
);

drop policy if exists "post_attachments_delete_own" on post_attachments;
create policy "post_attachments_delete_own"
on post_attachments for delete
using (
  exists (select 1 from posts pt where pt.id = post_id and pt.user_id = auth.uid())
);
