-- 페이지/게시판 방문 통계. 로그인한 회원이 페이지를 볼 때마다 한 줄씩 쌓고,
-- 관리자가 기간별로 어느 페이지·게시판 카테고리가 많이 쓰이는지 집계해서 본다.

create table if not exists page_views (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  path text not null,
  detail text,
  created_at timestamptz not null default now()
);

create index if not exists page_views_created_at_idx on page_views (created_at);
create index if not exists page_views_path_idx on page_views (path);

alter table page_views enable row level security;

drop policy if exists "page_views_insert_own" on page_views;
create policy "page_views_insert_own"
on page_views for insert
with check (user_id = auth.uid());

drop policy if exists "page_views_select_admin" on page_views;
create policy "page_views_select_admin"
on page_views for select
using (
  exists (select 1 from profiles p where p.id = auth.uid() and p.is_admin = true)
);
